# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG = arduino_due_x
ARCHITECTURE = sam
ARDUINO_PACKAGE_DIR := C:/Users/$(USER)/AppData/Local/Arduino15/packages

ARDUINO_DIR   	= /c/Arduino
MONITOR_PORT	= com3


include $(USERPROFILE)/OneDrive/Dokumente/Bachelorarbeit/Durchfuehrung/Arduino/Server/MakeFileRepo/MakeFile/Sam.mk
